use std::ops::Index;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mode {
    Implied,
    Accumulator,
    Immediate,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    Relative,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Indirect,
    IndirectX,
    IndirectY,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Code {
    ADC,
    AND,
    ASL,
    BCC,
    BCS,
    BEQ,
    BIT,
    BMI,
    BNE,
    BPL,
    BRK,
    BVC,
    BVS,
    CLC,
    CLD,
    CLI,
    CLV,
    CMP,
    CPX,
    CPY,
    DEC,
    DEX,
    DEY,
    EOR,
    INC,
    INX,
    INY,
    JMP,
    JSR,
    LDA,
    LDX,
    LDY,
    LSR,
    NOP,
    ORA,
    PHA,
    PHP,
    PLA,
    PLP,
    ROL,
    ROR,
    RTI,
    RTS,
    SBC,
    SEC,
    SED,
    SEI,
    STA,
    STX,
    STY,
    TAX,
    TAY,
    TSX,
    TXA,
    TXS,
    TYA,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct OpCode(pub Code, pub Mode, pub u8);

const OP_CODE: [(Code, Mode); 256] = [
    (Code::BRK, Mode::Implied),
    (Code::ORA, Mode::IndirectX),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::ORA, Mode::ZeroPage),
    (Code::ASL, Mode::ZeroPage),
    (Code::NOP, Mode::Implied),
    (Code::PHP, Mode::Implied),
    (Code::ORA, Mode::Immediate),
    (Code::ASL, Mode::Accumulator),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::ORA, Mode::Absolute),
    (Code::ASL, Mode::Absolute),
    (Code::NOP, Mode::Implied),
    (Code::BPL, Mode::Relative),
    (Code::ORA, Mode::IndirectY),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::ORA, Mode::ZeroPageX),
    (Code::ASL, Mode::ZeroPageX),
    (Code::NOP, Mode::Implied),
    (Code::CLC, Mode::Implied),
    (Code::ORA, Mode::AbsoluteY),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::ORA, Mode::AbsoluteX),
    (Code::ASL, Mode::AbsoluteX),
    (Code::NOP, Mode::Implied),
    (Code::JSR, Mode::Absolute),
    (Code::AND, Mode::IndirectX),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::BIT, Mode::ZeroPage),
    (Code::AND, Mode::ZeroPage),
    (Code::ROL, Mode::ZeroPage),
    (Code::NOP, Mode::Implied),
    (Code::PLP, Mode::Implied),
    (Code::AND, Mode::Immediate),
    (Code::ROL, Mode::Accumulator),
    (Code::NOP, Mode::Implied),
    (Code::BIT, Mode::Absolute),
    (Code::AND, Mode::Absolute),
    (Code::ROL, Mode::Absolute),
    (Code::NOP, Mode::Implied),
    (Code::BMI, Mode::Relative),
    (Code::AND, Mode::IndirectY),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::AND, Mode::ZeroPageX),
    (Code::ROL, Mode::ZeroPageX),
    (Code::NOP, Mode::Implied),
    (Code::SEC, Mode::Implied),
    (Code::AND, Mode::AbsoluteY),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::AND, Mode::AbsoluteX),
    (Code::ROL, Mode::AbsoluteX),
    (Code::NOP, Mode::Implied),
    (Code::RTI, Mode::Implied),
    (Code::EOR, Mode::IndirectX),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::EOR, Mode::ZeroPage),
    (Code::LSR, Mode::ZeroPage),
    (Code::NOP, Mode::Implied),
    (Code::PHA, Mode::Implied),
    (Code::EOR, Mode::Immediate),
    (Code::LSR, Mode::Accumulator),
    (Code::NOP, Mode::Implied),
    (Code::JMP, Mode::Absolute),
    (Code::EOR, Mode::Absolute),
    (Code::LSR, Mode::Absolute),
    (Code::NOP, Mode::Implied),
    (Code::BVC, Mode::Relative),
    (Code::EOR, Mode::IndirectY),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::EOR, Mode::ZeroPageX),
    (Code::LSR, Mode::ZeroPageX),
    (Code::NOP, Mode::Implied),
    (Code::CLI, Mode::Implied),
    (Code::EOR, Mode::AbsoluteY),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::EOR, Mode::AbsoluteX),
    (Code::LSR, Mode::AbsoluteX),
    (Code::NOP, Mode::Implied),
    (Code::RTS, Mode::Implied),
    (Code::ADC, Mode::IndirectX),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::ADC, Mode::ZeroPage),
    (Code::ROR, Mode::ZeroPage),
    (Code::NOP, Mode::Implied),
    (Code::PLA, Mode::Implied),
    (Code::ADC, Mode::Immediate),
    (Code::ROR, Mode::Accumulator),
    (Code::NOP, Mode::Implied),
    (Code::JMP, Mode::Indirect),
    (Code::ADC, Mode::Absolute),
    (Code::ROR, Mode::Absolute),
    (Code::NOP, Mode::Implied),
    (Code::BVS, Mode::Relative),
    (Code::ADC, Mode::IndirectY),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::ADC, Mode::ZeroPageX),
    (Code::ROR, Mode::ZeroPageX),
    (Code::NOP, Mode::Implied),
    (Code::SEI, Mode::Implied),
    (Code::ADC, Mode::AbsoluteY),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::ADC, Mode::AbsoluteX),
    (Code::ROR, Mode::AbsoluteX),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::STA, Mode::IndirectX),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::STY, Mode::ZeroPage),
    (Code::STA, Mode::ZeroPage),
    (Code::STX, Mode::ZeroPage),
    (Code::NOP, Mode::Implied),
    (Code::DEY, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::TXA, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::STY, Mode::Absolute),
    (Code::STA, Mode::Absolute),
    (Code::STX, Mode::Absolute),
    (Code::NOP, Mode::Implied),
    (Code::BCC, Mode::Relative),
    (Code::STA, Mode::IndirectY),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::STY, Mode::ZeroPageX),
    (Code::STA, Mode::ZeroPageX),
    (Code::STX, Mode::ZeroPageY),
    (Code::NOP, Mode::Implied),
    (Code::TYA, Mode::Implied),
    (Code::STA, Mode::AbsoluteY),
    (Code::TXS, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::STA, Mode::AbsoluteX),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::LDY, Mode::Immediate),
    (Code::LDA, Mode::IndirectX),
    (Code::LDX, Mode::Immediate),
    (Code::NOP, Mode::Implied),
    (Code::LDY, Mode::ZeroPage),
    (Code::LDA, Mode::ZeroPage),
    (Code::LDX, Mode::ZeroPage),
    (Code::NOP, Mode::Implied),
    (Code::TAY, Mode::Implied),
    (Code::LDA, Mode::Immediate),
    (Code::TAX, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::LDY, Mode::Absolute),
    (Code::LDA, Mode::Absolute),
    (Code::LDX, Mode::Absolute),
    (Code::NOP, Mode::Implied),
    (Code::BCS, Mode::Relative),
    (Code::LDA, Mode::IndirectY),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::LDY, Mode::ZeroPageX),
    (Code::LDA, Mode::ZeroPageX),
    (Code::LDX, Mode::ZeroPageY),
    (Code::NOP, Mode::Implied),
    (Code::CLV, Mode::Implied),
    (Code::LDA, Mode::AbsoluteY),
    (Code::TSX, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::LDY, Mode::AbsoluteX),
    (Code::LDA, Mode::AbsoluteX),
    (Code::LDX, Mode::AbsoluteY),
    (Code::NOP, Mode::Implied),
    (Code::CPY, Mode::Immediate),
    (Code::CMP, Mode::IndirectX),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::CPY, Mode::ZeroPage),
    (Code::CMP, Mode::ZeroPage),
    (Code::DEC, Mode::ZeroPage),
    (Code::NOP, Mode::Implied),
    (Code::INY, Mode::Implied),
    (Code::CMP, Mode::Immediate),
    (Code::DEX, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::CPY, Mode::Absolute),
    (Code::CMP, Mode::Absolute),
    (Code::DEC, Mode::Absolute),
    (Code::NOP, Mode::Implied),
    (Code::BNE, Mode::Relative),
    (Code::CMP, Mode::IndirectY),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::CMP, Mode::ZeroPageX),
    (Code::DEC, Mode::ZeroPageX),
    (Code::NOP, Mode::Implied),
    (Code::CLD, Mode::Implied),
    (Code::CMP, Mode::AbsoluteY),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::CMP, Mode::AbsoluteX),
    (Code::DEC, Mode::AbsoluteX),
    (Code::NOP, Mode::Implied),
    (Code::CPX, Mode::Immediate),
    (Code::SBC, Mode::IndirectX),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::CPX, Mode::ZeroPage),
    (Code::SBC, Mode::ZeroPage),
    (Code::INC, Mode::ZeroPage),
    (Code::NOP, Mode::Implied),
    (Code::INX, Mode::Implied),
    (Code::SBC, Mode::Immediate),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::CPX, Mode::Absolute),
    (Code::SBC, Mode::Absolute),
    (Code::INC, Mode::Absolute),
    (Code::NOP, Mode::Implied),
    (Code::BEQ, Mode::Relative),
    (Code::SBC, Mode::IndirectY),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::SBC, Mode::ZeroPageX),
    (Code::INC, Mode::ZeroPageX),
    (Code::NOP, Mode::Implied),
    (Code::SED, Mode::Implied),
    (Code::SBC, Mode::AbsoluteY),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::NOP, Mode::Implied),
    (Code::SBC, Mode::AbsoluteX),
    (Code::INC, Mode::AbsoluteX),
    (Code::NOP, Mode::Implied),
];

const CYCLE: [u8; 256] = [
    7, 6, 2, 8, 3, 3, 5, 5, 3, 2, 2, 2, 4, 4, 6, 6, 2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 6, 7,
    6, 6, 2, 8, 3, 3, 5, 5, 4, 2, 2, 2, 4, 4, 6, 6, 2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 6, 7,
    6, 6, 2, 8, 3, 3, 5, 5, 3, 2, 2, 2, 3, 4, 6, 6, 2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 6, 7,
    6, 6, 2, 8, 3, 3, 5, 5, 4, 2, 2, 2, 5, 4, 6, 6, 2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 6, 7,
    2, 6, 2, 6, 3, 3, 3, 3, 2, 2, 2, 2, 4, 4, 4, 4, 2, 6, 2, 6, 4, 4, 4, 4, 2, 4, 2, 5, 5, 4, 5, 5,
    2, 6, 2, 6, 3, 3, 3, 3, 2, 2, 2, 2, 4, 4, 4, 4, 2, 5, 2, 5, 4, 4, 4, 4, 2, 4, 2, 4, 4, 4, 4, 4,
    2, 6, 2, 8, 3, 3, 5, 5, 2, 2, 2, 2, 4, 4, 6, 6, 2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,
    2, 6, 3, 8, 3, 3, 5, 5, 2, 2, 2, 2, 4, 4, 6, 6, 2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,
];

impl OpCode {
    pub fn from(b: u8) -> Option<Self> {
        let &(code, mode) = OP_CODE.get(b as usize)?;
        let &cycle = CYCLE.get(b as usize)?;

        Some(Self(code, mode, cycle))
    }

    #[cfg(test)]
    pub fn to_bytes(&self) -> u8 {
        let index = OP_CODE.iter().position(|&x| x == (self.0, self.1)).unwrap();
        index as u8
    }
}
