name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # mainブランチへpushされたら実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # 1. Rustのセットアップ
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      # 2. Node.jsのセットアップ
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18 # 必要に応じてバージョンを変更

      - name: Install cargo-make
        run: cargo install cargo-make

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Install pnpm
        run: npm install -g pnpm

      # 3. ビルド (cargo-makeで一括実行想定)
      - name: Build (cargo-make)
        run: |
          rustup target add wasm32-unknown-unknown

          # cargo make で一括ビルド
          cargo make build-all

      - uses: actions/upload-pages-artifact@v3
        with:
          path: web/frontend/dist

  deploy:
    needs: build
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # アップロードされた成果物を GitHub Pages にデプロイ
      - uses: actions/deploy-pages@v4
        id: deployment
